# fly.toml app configuration file generated for garagevincentparrot on 2023-07-20T13:44:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "garagevincentparrot"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
